# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1889d522c051e0883d416f8df9984e061ddbaa630be2cf98eb81c4815b4c661f8df7e99b071a8b0eab56ff62fc7c57de72d6b2308ccf94f1ee931befda5c6a8d

test:
  secret_key_base: d8cdf926dfe04b9d3eae9bb1a3ba486fad9501cdd068460022bdf186d35c26809054bdc8c0e78896d2b5eff6b40a4682fa9fc83268325a0172ebd8bb69ed40ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
